---

num_rounds: 5000 # number of FL rounds in the experiment
num_clients: 50 # number of total clients available (this is also the number of partitions we need to create)
batch_size: 64 # batch size to use by clients during training
num_classes: 10 # number of classes in our dataset (we use MNIST) -- this tells the model how to setup its output fully-connected layer
num_clients_per_round_fit: 10 # number of clients to involve in each fit round (fit  round = clients receive the model from the server and do local training)
num_clients_per_round_eval: 10 # number of clients to involve in each evaluate round (evaluate round = client only evaluate the model sent by the server on their local dataset without training it)
config_fit: # a config that each client will receive (this is send by the server) when they are sampled. This allows you to dynamically configure the training on the client side as the simulation progresses
  lr: 0.01 # learning rate to use by the clients
  momentum: 0.9 # momentum used by SGD optimiser on the client side
  local_epochs: 1

alpha: 1e-2
beta: 1e-3
global_epochs: 200
local_epochs: 4
pers_epochs: 1
hf: 1
validation_ratio: 0.1
Client_num_per_node: 10
seed: 17
eval_while_training: 1